// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vlpddr4_sim_tb.h for the primary calling header

#ifndef VERILATED_VLPDDR4_SIM_TB___024ROOT_H_
#define VERILATED_VLPDDR4_SIM_TB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vlpddr4_sim_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vlpddr4_sim_tb___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ lpddr4_sim_tb__DOT__sys_clk;
        CData/*0:0*/ lpddr4_sim_tb__DOT__sys_rst_n;
        CData/*0:0*/ lpddr4_sim_tb__DOT__pll_lock;
        CData/*0:0*/ lpddr4_sim_tb__DOT__ddr_clk;
        CData/*0:0*/ lpddr4_sim_tb__DOT__ddr_clk_4x;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s0_axi_wready;
        CData/*3:0*/ lpddr4_sim_tb__DOT__s0_axi_bid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s0_axi_bresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s0_axi_bvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s0_axi_arready;
        CData/*4:0*/ lpddr4_sim_tb__DOT__s0_axi_rid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s0_axi_rresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s0_axi_rlast;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s0_axi_rvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s1_axi_wready;
        CData/*3:0*/ lpddr4_sim_tb__DOT__s1_axi_bid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s1_axi_bresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s1_axi_bvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s1_axi_arready;
        CData/*4:0*/ lpddr4_sim_tb__DOT__s1_axi_rid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s1_axi_rresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s1_axi_rlast;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s1_axi_rvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s2_axi_wready;
        CData/*3:0*/ lpddr4_sim_tb__DOT__s2_axi_bid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s2_axi_bresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s2_axi_bvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s2_axi_arready;
        CData/*4:0*/ lpddr4_sim_tb__DOT__s2_axi_rid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s2_axi_rresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s2_axi_rlast;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s2_axi_rvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s3_axi_wready;
        CData/*3:0*/ lpddr4_sim_tb__DOT__s3_axi_bid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s3_axi_bresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s3_axi_bvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s3_axi_arready;
        CData/*4:0*/ lpddr4_sim_tb__DOT__s3_axi_rid;
        CData/*1:0*/ lpddr4_sim_tb__DOT__s3_axi_rresp;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s3_axi_rlast;
        CData/*0:0*/ lpddr4_sim_tb__DOT__s3_axi_rvalid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__psel;
        CData/*0:0*/ lpddr4_sim_tb__DOT__penable;
        CData/*7:0*/ lpddr4_sim_tb__DOT__paddr;
        CData/*0:0*/ lpddr4_sim_tb__DOT__pwrite;
        CData/*0:0*/ lpddr4_sim_tb__DOT__training_done;
        CData/*0:0*/ lpddr4_sim_tb__DOT__tg_enable;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s0_axi_awready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s0_axi_bready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s1_axi_awready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s1_axi_bready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s2_axi_awready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s2_axi_bready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s3_axi_awready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__s3_axi_bready;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__rst_n;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__ddr_rst_n;
        CData/*1:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__dfi_cke;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__dfi_wrdata_en;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__dfi_wrdata_mask;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cmd_len;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cmd_wr;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cmd_id;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__resp_ready;
    };
    struct {
        CData/*1:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__resp_port;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__training_done_int;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__training_fail;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__wl_delay;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__gate_delay;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__rd_delay;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__wr_delay;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__ca_delay;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT____Vcellout__u_controller__dfi_cs_n;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__ddr_dqs__en1;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_crossbar__DOT__port_req;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_crossbar__DOT__port_gnt;
        CData/*1:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_crossbar__DOT__grant_enc;
        CData/*1:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_crossbar__DOT__arb_rr;
        CData/*1:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_crossbar__DOT__port_pri;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_crossbar__DOT__rot_req;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__intr_err;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__state;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__next_state;
        CData/*2:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__bank_addr;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_valid;
        CData/*2:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wr_ptr;
        CData/*2:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_rd_ptr;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_full;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_empty;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__burst_cnt;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__burst_active;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__rob_head;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__rob_tail;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__rob_pending_id;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__timer_done;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__timer_start;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__init_timer;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__ref_req;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__ref_ack;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ck_enable;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ck_gate;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ca_load;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ca_cnt;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dqs_in;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ser_cnt;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__deser_cnt;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__wrdata_en_dly;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__wrdata_cnt;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__rddata_en;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__rddata_cnt;
        CData/*2:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__rd_phase;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dqs_gate;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dqs_gate_early;
        CData/*1:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__odt_reg;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__init_reset_n;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__reset_phy_latch;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dqs_toggle;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__prev_dfi_rddata_en;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs__out__strong__out32;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs__out__strong__out33;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs__out__strong__out34;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs__out__strong__out35;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs_n__out__strong__out36;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs_n__out__strong__out37;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs_n__out__strong__out38;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dqs_n__out__strong__out39;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__rst_n;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__state_machine;
    };
    struct {
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__next_state;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__dq_out_en;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__dqs_out;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__timer;
        CData/*1:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__bank_addr_reg;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__timer_init;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__timer_load;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__enable;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__state;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__next_state;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__lfsr_feedback;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__curr_len;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__curr_arid;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__curr_awid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__is_write;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__beat_count;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__state;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__next_state;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__lfsr_feedback;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__curr_len;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__curr_arid;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__curr_awid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__is_write;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__beat_count;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__state;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__next_state;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__lfsr_feedback;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__curr_len;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__curr_arid;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__curr_awid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__is_write;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__beat_count;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__state;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__next_state;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__lfsr_feedback;
        CData/*7:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__curr_len;
        CData/*4:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__curr_arid;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__curr_awid;
        CData/*0:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__is_write;
        CData/*3:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__beat_count;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_0;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_5;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_6;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_7;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_8;
        CData/*2:0*/ __Vdly__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_rd_ptr;
        CData/*7:0*/ __Vdly__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__burst_cnt;
        CData/*3:0*/ __Vdly__lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__rddata_cnt;
        CData/*0:0*/ __VdlySet__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_addr__v0;
        CData/*7:0*/ __VdlyVal__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_len__v0;
        CData/*2:0*/ __VdlyDim0__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_len__v0;
        CData/*2:0*/ __VdlyDim0__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wdata__v0;
        CData/*2:0*/ __VdlyDim0__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wstrb__v0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__u_dut__DOT__s3_axi_bready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__u_dut__DOT__s2_axi_bready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__u_dut__DOT__s1_axi_bready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__u_dut__DOT__s0_axi_bready__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__ddr_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__sys_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__ddr_clk_4x__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__u_mem__DOT__rst_n__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__sys_rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lpddr4_sim_tb__DOT__pll_lock__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VinactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*9:0*/ lpddr4_sim_tb__DOT__ddr_ca;
        SData/*9:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__dfi_ca;
        SData/*15:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cmd_wstrb;
        SData/*15:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__write_strb_buf;
        SData/*15:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__timer;
        SData/*15:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__ref_timer;
        SData/*9:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ca_shreg;
        SData/*13:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__cmd_addr;
        SData/*15:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__row_addr_reg;
        SData/*9:0*/ __Vdly__lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ca_shreg;
        SData/*15:0*/ __VdlyVal__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wstrb__v0;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__s0_axi_rdata;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__s1_axi_rdata;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__s2_axi_rdata;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__s3_axi_rdata;
        IData/*31:0*/ lpddr4_sim_tb__DOT__pwdata;
        IData/*31:0*/ lpddr4_sim_tb__DOT__prdata;
        IData/*31:0*/ lpddr4_sim_tb__DOT__ddr_clk_count;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_0__stat_write_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_0__stat_read_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_0__stat_writes;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_0__stat_reads;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_1__stat_write_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_1__stat_read_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_1__stat_writes;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_1__stat_reads;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_2__stat_write_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_2__stat_read_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_2__stat_writes;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_2__stat_reads;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_3__stat_write_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_3__stat_read_cmds;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_3__stat_writes;
        IData/*31:0*/ lpddr4_sim_tb__DOT____Vcellout__u_tg_3__stat_reads;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__ddr_dq;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__dfi_wrdata;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cmd_addr;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cmd_wdata;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cfg_ctrl;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cfg_timing;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cfg_phy;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__cfg_training;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__write_buf;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__read_buf;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dq_out;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dq_in;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__rd_aligned;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__wr_data_buf;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__rd_data_buf;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out0;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out1;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out2;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out3;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out4;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out5;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out6;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out7;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out8;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out9;
    };
    struct {
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out10;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out11;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out12;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out13;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out14;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out15;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out16;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out17;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out18;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out19;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out20;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out21;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out22;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out23;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out24;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out25;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out26;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out27;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out28;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out29;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out30;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__ddr_dq__out__strong__out31;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__read_data;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__unnamedblk2__DOT__mem_idx;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out0;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out1;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out2;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out3;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out4;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out5;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out6;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out7;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out8;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out9;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out10;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out11;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out12;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out13;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out14;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out15;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out16;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out17;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out18;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out19;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out20;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out21;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out22;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out23;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out24;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out25;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out26;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out27;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out28;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out29;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out30;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_mem__DOT__ddr_dq__out__strong__out31;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT____VlemCall_0__random;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__lfsr;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__curr_addr;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_tg_0__DOT__curr_wdata;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT____VlemCall_0__random;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__lfsr;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__curr_addr;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_tg_1__DOT__curr_wdata;
    };
    struct {
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT____VlemCall_0__random;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__lfsr;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__curr_addr;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_tg_2__DOT__curr_wdata;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT____VlemCall_0__random;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__lfsr;
        IData/*31:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__curr_addr;
        VlWide<4>/*127:0*/ lpddr4_sim_tb__DOT__u_tg_3__DOT__curr_wdata;
        VlWide<4>/*127:0*/ __VdlyVal__lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wdata__v0;
        IData/*31:0*/ __VactIterCount;
        IData/*31:0*/ __VinactIterCount;
        IData/*31:0*/ __Vi;
        VlUnpacked<IData/*31:0*/, 4> lpddr4_sim_tb__DOT__stat_reads;
        VlUnpacked<IData/*31:0*/, 4> lpddr4_sim_tb__DOT__stat_writes;
        VlUnpacked<IData/*31:0*/, 4> lpddr4_sim_tb__DOT__stat_read_cmds;
        VlUnpacked<IData/*31:0*/, 4> lpddr4_sim_tb__DOT__stat_write_cmds;
        VlUnpacked<VlUnpacked<SData/*13:0*/, 2>, 4> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__open_row;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 4> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__row_open;
        VlUnpacked<IData/*31:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_addr;
        VlUnpacked<CData/*7:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_len;
        VlUnpacked<CData/*0:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wr;
        VlUnpacked<VlWide<4>/*127:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wdata;
        VlUnpacked<SData/*15:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_wstrb;
        VlUnpacked<CData/*4:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_id;
        VlUnpacked<CData/*1:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__q_port;
        VlUnpacked<VlWide<4>/*127:0*/, 32> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__rob_rdata;
        VlUnpacked<CData/*4:0*/, 32> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__rob_id;
        VlUnpacked<CData/*0:0*/, 32> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__rob_valid;
        VlUnpacked<CData/*7:0*/, 64> lpddr4_sim_tb__DOT__u_dut__DOT__u_controller__DOT__mr;
        VlUnpacked<CData/*3:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dq_ser;
        VlUnpacked<CData/*3:0*/, 4> lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dqs_ser;
        VlUnpacked<CData/*3:0*/, 8> lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dq_deser;
        VlUnpacked<CData/*3:0*/, 4> lpddr4_sim_tb__DOT__u_dut__DOT__u_phy__DOT__dqs_deser;
        VlUnpacked<IData/*31:0*/, 268435456> lpddr4_sim_tb__DOT__u_mem__DOT__mem;
        VlUnpacked<SData/*15:0*/, 4> lpddr4_sim_tb__DOT__u_mem__DOT__open_row;
        VlUnpacked<CData/*0:0*/, 4> lpddr4_sim_tb__DOT__u_mem__DOT__open_bank;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 9> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h885c11dc__0;
    VlTriggerScheduler __VtrigSched_h555bb969__0;
    VlTriggerScheduler __VtrigSched_hcd29c994__0;

    // INTERNAL VARIABLES
    Vlpddr4_sim_tb__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vlpddr4_sim_tb___024root(Vlpddr4_sim_tb__Syms* symsp, const char* namep);
    ~Vlpddr4_sim_tb___024root();
    VL_UNCOPYABLE(Vlpddr4_sim_tb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
